import { Link } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Lozatel :)
        </h1>

        <p className={styles.description}>
          Lozatel is a friendly atlas developed and designed by Rizki Anandar Saputra and team for the purpose of the research. <br/>
          Lozatel primary objective is to serve data from Badan Pusat Statistika Indonesia into a friendly and interesting display <br/>
          So anyone can read it without too much effort on the processing the raw data.
        </p>

        <div className={styles.grid}>
          <a href="/dashboard" className={styles.card}>
            <h2>Dashboard &rarr;</h2>
            <p>Treemap is the best we can show it for now</p>
          </a>

          <a href="/aboutus" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Find About Us</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
